const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "2348101699340"
const SESSION_ID = "PRABATH-MD~eKokmJxI#rfAFjrwaIW4tRTkDTpjJbJ46wbkoQwN7AETyvDxOkCc"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
