const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "2348101699340"
const SESSION_ID = "PRABATH-MD~eKokmJxI#rfAFjrwaIW4tRTkDTpjJbJ46wbkoQwN7AETyvDxOkCc"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
